# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide

description: "LLM 모델 비교 실험 - 프롬프트별 성능 평가"

prompts:
  - file://./prompts/summary/summary_prompt.txt
  - file://./prompts/summary/twitter_style_prompt.txt

providers:
  - file://./conf/providers/openai.yaml
  - file://./conf/providers/google.yaml
  - file://./conf/providers/perplexity.yaml
  # - file://./conf/providers/ollama.yaml

# 자동 조합을 위한 기본 설정
defaultTest:
  vars:
    query: "Test Time Compute, Reasoning, LLM Agents 최신 연구"
    temperature: 0.7
  assert:
    - type: "llm-rubric"
      value: |
        평가 기준:
        1. 정보성 (2점)
           - 핵심 내용 포함
           - 실용적 조언
        2. 논리성 (2점)
           - 논리적 흐름
           - 일관된 설명
        총점 3점 이상 합격

tests: file://./tests/test.csv

outputs:
  - type: "csv"
    file: "./outputs/test.csv"